import { LangPack } from "./LangPack";

export const arabic: LangPack = {

    "language_own_name" : "عربي",
    "app_name": "بسيتاكوس",
    "support_email": "luxlunarislabs@gmail.com",
    "home": "بيت",
    "take_lesson": "خذ درس",
    "craft_new_lesson": "إصنع درس جديد",
    "edit_lesson": "عدل درس",
    "info": "معلومات",
    "settings": "إعدادات",
    "choose_lang": "لغة",
    "edit_metadata": "عدل البيانات الوصفية",
    "save_lesson": "إحفظ الدرس",
    "previous_sentence": "الجملة السابقة",
    "next_sentence": "الجملة التالية",
    "write_and_pronounce": "قلها",
    "target_lang_is": "إكتب و إنطق جملة بالغة الهدف: أي اللغة التي طلابك يودون أن يتعلموا",
    "record": "سجل",
    "play_audio": "إسمع",
    "translate_to_source_lang": "ترجمها",
    "source_lang_is": "ترجم الجملة بالغة الطلاب الأصلية",
    "write_word_dict": "معجم",
    "words_will_appear": "الكلمات ستظهر هنا و أنت تكتب الجملة",
    "words_will_appear_word_dict": "الكلمات ستظهر هنا و أنت تكتب الجملة",
    "write_reverse_dict": "معجم عكسي",
    "words_will_appear_reverse_dict": "ترجم كل كلمة من لغة طلابك إلى اللغة التي يتعلمونها",
    "choose_translation_direction": "إتجاه",
    "translation_direction_is": "في الأصل سيسأل طلابك أن يترجموا من لغة الهدف إلى لغتهم و يمكنك أن تغير ذلك بالضغت على هذا الزر",
    "choose_word_buttons": "أزرار الكلمات",
    "word_buttons_is": ":بدلا من كتابة الإجابة الطلاب سيستخدمون أزرار مكتوب عليها الكلمات",
    "extra_words": "كلمات إضافية",
    "extra_words_are": "هذه الكلمات هدفها إرباك الطالب و جعل الإجابة أصعب عند إستخدامه أزرار الكلمات",
    "your_answer": "إجابتك",
    "available_words": "كلمات متوفرة",
    "translate_this_sentence": ":ترجم الجملة:",
    "see_solution": "أرى الإيجابة",
    "solution": "إيجابة",
    "your_accuracy": "دقتك",
    "next": "تالي",
    "to_use_app_offline": "html لإستخدام التطبيق بدون شبكة قم بتنزيل الصفحة كوثيقة",
    "win_linux_save_offline": "Ctrl+S :ويندوس/لينكس",
    "mac_save_offline": "⌘ + S :ماك",
    "link_to_source_code_title": "كود مصدري",
    "link_to_source_code": "https://github.com/aiman-al-masoud/psittacus",
    "welcome": "!مرحبا بك/ي على بسيتاكوس",
    "license_notice": "GPLv3 أيمن المسعود © 2022 - بسيتاكوس سوفتوير حر تحت رخصة",
    "your_work_may_be_lost": "ستخسر عملك اوك",
    "stop_recording": "وقف التسجيل",
    "metadata": "بيانات وصفية",
    "overall_accuracy": ":إجمالي الدقة",
    "thank_you_for_taking_lesson": "!شكرا لأخذك الدرس",
    "need_a_tip_hover_words": "تريد نصيحة؟ أشر إلى كلمة لا تعرفها بالماوس",
    "edit_sentences": "عدل الجمل",
    "edit_explanation": "عدل الشرح",
    "make_your_point": "إشرح",
    "make_your_point_is": "أمنح طلابك شرحا مفصلا",
    "read_explanation": "إقرأ الشرح",
    "back": "عد",
    "need_a_lot_of_tips": ":تريد نصائح كثيرة؟ :-) عد إلى الشرح النظري",
    "use_html_tags": "إستخدم الhtml لترتيب و تزين النص",
    "demo": "عرض تقديمي (بالإجليزي)",
    "demo_link": "https://youtu.be/estAGLc3uoE",
    "license": "رخصة",
    "license_link": "https://github.com/aiman-al-masoud/psittacus/blob/main/LICENSE",
    "full_terms": "الرخصة الكاملة",
    "shortcuts": "إختصارات",
    "lesson_crafting": "صنع الدروس",
    "shortcut_save_lesson": "Ctrl+S",
    "shortcut_record_audio": "Ctrl+Spazio",
    "shortcut_play_audio": "Shift+Spazio",
    "tab_to_move": "Tab للعنصر التالي Shift+Tab للسابق",
    "choose_proposition_scheduler": "مجدول الإقتراحات",
    "proposition_scheduler_is": "مجدول الإقتراحات يختار ترتيب و تكرار الإقتراحات أثناء الدرس",
    "manage_data_about_your_progress": "إدارة تقدمك",
    "progress_is": "هذه البيانات محفوظة على جهازك فقط, و تساعد بسيتاكوس على تقديمك تجربة أفضل بالتكرار المتباعد",
    "export_progress": "صدر تقدمك",
    "import_progress": "استورد تقدمك",
    "erase_progress": "الغي تقدمك",
    "make_sure_title_is_unique": "كل دروسك يجب أن تكون لها اسم واحد, الأسم سيستخدم لتعريف كل درس عن باقي الدروس التي أنتجتها أنت",
    "history": "تاريخ",
    "revise": "!راجع",
    "choose_lesson_scheduler": "مجدول الدروس",
    "lesson_scheduler_is": "مجدول الدروس يقترح درس للمراجعة حسب البيانات المحفوظة على جهازك",
    "please_complete_metadata": "!اكمل البيانات الوصفية قبل تخزين الدرس",
    "confirm_send_bug_report": "ارسل بج ريبورت؟",
    "errors_text": "نص الإشكال",
    "psittacus_bug_report": "بسيتاكوس بج ريبورت",
    "send_bug_report": "ارسل بج ريبورت",
    "bug_reports": "بج ريبورت",
    "bug_report_is": ":لو وجدت مشكلة, يمكنك أن تتواصل معنا عن طريق البريد الإليكتروني",
    "issue_is": ":github أو يمكنك أن تتواصل معنا على الريبو الرسمي على موقع",
    "file_issue": "تقديم المشكلة",
    "revise_with_lesson_scheduler": "مراجعة",
    "lessons_history": "تاريخ",
    "revise_with_lesson_scheduler_is": "مجدولك سيقرر الدرس القادم لك للمراجعة",
    "history_here": "الدروس المأخوذة ستظهر هنا",
    "until_all_correct_PS": "سيعد مأخرا الى الأسئلة التي لم تصب فيها, و لن يجعلك تخرج حتى تجيب بشكل صحيح",
    "worst_first_PS": "يتذكر الإقتراحات التي وجدت فيها صعوبة أكثر المرة السابقة, و يقدمها إلى الأمام",
    "mixed_worst_lesson_LS": "يخلط الإقتراحات من أكثر من درس, مقدما الجمل الأصعب الى الأمام",
    "oldest_lesson_first_LS": "يقترح الدرس الأقدم",
    "worst_lesson_first_LS": "يقترح الدرس الأصعب",
    "developer_options": "إعدادات المطور",
    "enable": "شغل",
    "caution_enabling_developer_options": "تحذير! تشغيل إعدادات المطور ربما يعرضك إلى خواطر",
    "run_custom_code": "شغل الكود المخصص",
    "caution_running_custom_code": "!تشغيل كود من مصادر غير موثقة أمر خطير: تأكد من فهمك للذي يجري",
    "add_custom_proposition_scheduler": "اضف مجدول اقتراحات مخصص",
    "add_custom_lesson_scheduler":  "اضف مجدول دروس مخصص",
    "template": "نموذج",
    "click_reload_or_remove_custom_code": "اضغط 'إعادة تحميل' بعد اضافة الكود المخصص, أو 'أزالة جميع الكود المخصص' لو غيرت رأيك.",
    "remove_all_custom_code": "أزالة جميع الكود المخصص",
    "dev_options_reload": "اعادة تحميل",
    "target_language": "لغة الهدف",
    "source_language": "لغة الأصل",
    "author": "مؤلف",
    "title": "عنوان",
    "filters": "منقي",
    "are_you_sure_delete_progress": "هل أنت متأكد من حذف تقدمك؟",
    "are_you_sure_enable_dev_options": "!تشغيل وضع المطور؟ من الممكن أن يعضرك للخطر",
    "download_lessons": "تنزيل الدروس",
    "here_you_can_search_for_and_download": "هنا يمكنك أن تبحث و تنزل الدروس المتورة على هذا السرفر",
    "images_sounds": "صور/اصوات",
    "attribs_link": "https://github.com/aiman-al-masoud/psittacus/blob/main/psittacus/app/res/attribs.md",
    "click_to_open": "اضغط لتفتح",
    "current_sentence": "الجملة الحالية / جميع الجمل",
    "target_to_native": "هدف إل أصل",
    "input_type_is": "إختر ما بين أن تكتب الإيجابة أو أن تستخدم ازرار الكلمات",
    "input_type" : "نوع الإدخال"


}
