import { LangPack } from "./LangPack";

export const chinese: LangPack = {

    "app_name": "Psittacus",
    "support_email": "luxlunarislabs@gmail.com",
    "home": "主页",
    "take_lesson": "学习",
    "craft_new_lesson": "构建新课程",
    "edit_lesson": "编辑课程",
    "info": "信息",
    "settings": "设置",
    "choose_lang": "语言",
    "edit_metadata": "编辑元数据",
    "save_lesson": "上课",
    "previous_sentence": "上一句",
    "next_sentence": "下一句",
    "write_and_pronounce": "说话",
    "target_lang_is": "用目标语言对一个句子进行书写和发音，即：您的学生希望学习的语言。",
    "record": "记录",
    "play_audio": "播放音频",
    "translate_to_source_lang": "翻译",
    "source_lang_is": "将句子翻译成源语言，即：学生可以理解的的语言。",
    "write_word_dict": "字典",
    "words_will_appear_word_dict": "以学生能够理解的方式解释您使用的每个单词。",
    "words_will_appear": "当您键入句子时，单词将出现在此处。",
    "write_reverse_dict": "反向字典",
    "words_will_appear_reverse_dict": "提供单词, 从学生使用的语言到他们正在学习的语言的翻译。",
    "choose_translation_direction": "方向",
    "translation_direction_is": "默认情况下，将要求学生从目标语言翻译到源语言。但是您可以通过取消选中此框来更改它：",
    "choose_word_buttons": "单词按钮",
    "word_buttons_is": "不要使用文本框，而是为用户提供按钮中的单词以使其按顺序排列：",
    "extra_words": "额外单词",
    "extra_words_are": "这些是额外的单词，在使用单词按钮时会误导学生",
    "your_answer": "你的答案",
    "available_words": "可选单词",
    "translate_this_sentence": "翻译这句话：",
    "see_solution": "查看检查方案",
    "solution": "解决方案",
    "your_accuracy": "你的准确率",
    "next": "下一个",
    "to_use_app_offline": "要离线使用此应用程序，只需将其另存为 .html 文件：",
    "win_linux_save_offline": "Windows/Linux: Ctrl + S",
    "mac_save_offline": "Mac: ⌘ + S",
    "link_to_source_code_title": "源代码",
    "link_to_source_code": "https://github.com/aiman-al-masoud/psittacus",
    "welcome": "欢迎来到 Psittacus!",
    "license_notice": "Aiman Al Masoud - © 2022 - Psittacus is free software, licensed under GNU GPLv3.",
    "your_work_may_be_lost": "可能会丢失正在进行的工作。确认吗？",
    "stop_recording": "停止录制",
    "metadata": "元数据",
    "overall_accuracy": "总正确率：",
    "thank_you_for_taking_lesson": "感谢学习",
    "need_a_tip_hover_words": "需要提示？将鼠标悬停在你不知道的单词上！",
    "edit_sentences": "编辑句子",
    "edit_explanation": "编辑解释",
    "make_your_point": "重点",
    "make_your_point_is": "让您的学生更深入地了解您在本课程中处理的主题。",
    "read_explanation": "阅读说明",
    "back": "返回",
    "need_a_lot_of_tips": "需要一些提示？:-)回到本课的理论部分：",
    "use_html_tags": "使用 html 标记来设置内容的样式。",
    "demo": "Demo",
    "demo_link": "https://youtu.be/estAGLc3uoE",
    "license": "许可证",
    "license_link": "https://github.com/aiman-al-masoud/psittacus/blob/main/LICENSE",
    "full_terms": "完整条款",
    "shortcuts": "快照",
    "lesson_crafting": "创建课程",
    "shortcut_save_lesson": "Ctrl+S",
    "shortcut_record_audio": "Ctrl+Space",
    "shortcut_play_audio": "Shift+Space",
    "tab_to_move": "按 Tab 键切换到下一个元素，Shift+Tab 用于上一个元素。",
    "choose_proposition_scheduler": "命题调度器",
    "proposition_scheduler_is": "命题调度器决定在课程中向您显示命题的顺序和频率。",
    "manage_data_about_your_progress": "管理进度",
    "progress_is": "这些数据包括您进行的练习的分数，它仅存储在您的本地机器上，它有助于 Psittacus 为您提供更好的间隔重复体验。",
    "export_progress": "导出进度",
    "import_progress": "导入进度",
    "erase_progress": "擦除进度",
    "make_sure_title_is_unique": "确保您制作的任何新课程都有一个唯一的标题：因为它将用于识别它",
    "history": "历史",
    "revise": "回顾！",
    "choose_lesson_scheduler": "课程安排器",
    "lesson_scheduler_is": "课程安排程序会随时建议您修改哪些课程。",
    "please_complete_metadata": "请在保存前完成本课程的元数据！",
    "confirm_send_bug_report": "发送错误报告？",
    "errors_text": "错误文本",
    "psittacus_bug_report": "Psittacus 错误报告",
    "send_bug_report": "发送错误报告",
    "bug_reports": "错误报告",
    "bug_report_is": "如果您发现问题，可以通过电子邮件向我们发送错误报告：",
    "issue_is": "或者，您可以将其作为问题提交到 Psittacus 的官方 Github 存储库中：",
    "file_issue": "提交一个问题 (issue)",
    "revise_with_lesson_scheduler": "回顾",
    "lessons_history": "课程历史",
    "revise_with_lesson_scheduler_is": "让您当前的课程安排程序决定您现在应该复习哪些课程/部分课程。",
    "history_here": "您过去参加的课程将显示在此处：",
    "until_all_correct_PS": "开始重温错题直到全对为止。",
    "worst_first_PS": "记住你上次最挣扎的命题，并且先游玩他们。",
    "mixed_worst_lesson_LS": "将你最挣扎的命题与你已经上过的许多不同的课程结合起来。",
    "oldest_lesson_first_LS": "让您重温您上过的最旧的课程。",
    "worst_lesson_first_LS": "让您重温您最难上过的一堂课。",
    "developer_options": "开发者选项",
    "enable": "启用",
    "caution_enabling_developer_options": "警告：启用开发人员选项可能会使您面临安全风险。",
    "run_custom_code": "运行自定义代码",
    "caution_running_custom_code": "从不受信任的来源运行代码是危险的：确保您知道自己在做什么！",
    "add_custom_proposition_scheduler": "添加自定义命题调度程序",
    "add_custom_lesson_scheduler": "添加自定义课程安排程序",
    "template": "模板",
    "click_reload_or_remove_custom_code": "添加自定义代码后单击“重新加载”，或者如果您改变主意，请单击“删除所有自定义代码”。",
    "remove_all_custom_code": "删除所有自定义代码",
    "dev_options_reload": "重载",
    "target_language": "目标语言",
    "source_language": "源语言",
    "author": "作者",
    "title": "标题",
    "filters": "过滤器",
    "are_you_sure_delete_progress": "是否确实要删除进度？",
    "are_you_sure_enable_dev_options": "启用开发模式？这可能会使您面临安全风险！",
    "download_lessons": "下载课程",
    "here_you_can_search_for_and_download": "在这里，您可以搜索和下载此服务器上托管的课程。",
    "images_sounds": "图片 / 声音",
    "attribs_link": "https://github.com/aiman-al-masoud/psittacus/blob/main/psittacus/app/res/attribs.md",
    "click_to_open": "点击以打开",
    "current_sentence": "当前句子 / 总句子",
    "target_to_native": "目标语言到源语言",
    "input_type_is": "选择是键入解决方案，还是使用课程提供的单词提示。",
    "input_type" : "Input Type"

}