export const english = {

    "app_name": "Psittacus",
    "support_email": "luxlunarislabs@gmail.com",
    "home": "Home",
    "take_lesson": "Take Lesson",
    "craft_new_lesson": "Craft New Lesson",
    "edit_lesson": "Edit Lesson",
    "info": "Info",
    "settings": "Settings",
    "choose_lang": "Language",
    "edit_metadata": "Edit Metadata",
    "save_lesson": "Save Lesson",
    "previous_sentence": "Previous Sentence",
    "next_sentence": "Next Sentence",
    "write_and_pronounce": "Say it",
    "target_lang_is": "Write and pronounce a sentence in the target language, that is: the language that your students wish to learn.",
    "record": "Record",
    "play_audio": "Play Audio",
    "translate_to_source_lang": "Translate it",
    "source_lang_is": "Translate the sentence to the source language, that is: the language that your students understand.",
    "write_word_dict": "Dictionary",
    "words_will_appear_word_dict": "Explain each word you used in a manner that your students will understand.",
    "words_will_appear": "Words will appear here as you type in the sentence.",
    "write_reverse_dict": "Reverse Dictionary",
    "words_will_appear_reverse_dict": "Provide a translation of the words from your students language to the language they're learning.",
    "choose_translation_direction": "Direction",
    "translation_direction_is": "By default students will be asked to translate from target to source. But you can change that by un-checking this box:",
    "choose_word_buttons": "Word buttons",
    "word_buttons_is": "Rather than using a text box, provide the users the words in buttons to put them in order:",
    "extra_words": "Extra words",
    "extra_words_are": "These are extra words to mislead the student when using word buttons",
    "your_answer": "Your answer",
    "available_words": "Available words",
    "translate_this_sentence": "Translate this sentence:",
    "see_solution": "See Solution",
    "solution": "Solution",
    "your_accuracy": "Your Accuracy",
    "next": "Next",
    "to_use_app_offline": "To use this app offline, just save it as a .html:",
    "win_linux_save_offline": "Windows/Linux: Ctrl + S",
    "mac_save_offline": "Mac: ⌘ + S",
    "link_to_source_code_title": "Source Code",
    "link_to_source_code": "https://github.com/aiman-al-masoud/psittacus",
    "welcome": "Welcome to Psittacus!",
    "license_notice": "Aiman Al Masoud - © 2022 - Psittacus is free software, licensed under GNU GPLv3.",
    "your_work_may_be_lost": "Your work may be lost. Ok?",
    "stop_recording": "Stop Recording",
    "metadata": "Metadata",
    "overall_accuracy": "Overall Accuracy:",
    "thank_you_for_taking_lesson": "Thank you for taking this lesson",
    "need_a_tip_hover_words": "Need a tip? Hover over a word you don't know!",
    "edit_sentences": "Edit Sentences",
    "edit_explanation": "Edit Explanation",
    "make_your_point": "Drive the point home.",
    "make_your_point_is": "Give your students some more in-depth insight on the topic(s) you're dealing with in this lesson.",
    "read_explanation": "Read Explanation",
    "back": "Back",
    "need_a_lot_of_tips": "Need a lot of tips? :-) Go back to this lesson's theory:",
    "use_html_tags": "Use html tags to style your content.",
    "demo": "Demo",
    "demo_link": "https://youtu.be/estAGLc3uoE",
    "license": "License",
    "license_link": "https://github.com/aiman-al-masoud/psittacus/blob/main/LICENSE",
    "full_terms": "Full Terms",
    "shortcuts": "Shortcuts",
    "lesson_crafting": "Lesson Crafting",
    "shortcut_save_lesson": "Ctrl+S",
    "shortcut_record_audio": "Ctrl+Space",
    "shortcut_play_audio": "Shift+Space",
    "tab_to_move": "Tab to switch to the next element, Shift+Tab for the previous.",
    "choose_proposition_scheduler": "Proposition Scheduler",
    "proposition_scheduler_is": "The Proposition Scheduler decides the order and the frequency in which Propositions are shown to you in during a Lesson.",
    "manage_data_about_your_progress": "Manage Progress",
    "progress_is": "This data includes your scores on the exercises you take, it is only stored locally on your machine, and it helps Psittacus in providing you with a better spaced-repetition experience.",
    "export_progress": "Export Progress",
    "import_progress": "Import Progress",
    "erase_progress": "Erase Progress",
    "make_sure_title_is_unique": "Make sure any new lesson you craft has a unique title: as it will be used to identify it",
    "history": "History",
    "revise": "Review!",
    "choose_lesson_scheduler": "Lesson Scheduler",
    "lesson_scheduler_is": "The Lesson Scheduler suggests you what Lesson you should revise at any time.",
    "please_complete_metadata": "Please complete this lesson's metadata before saving!",
    "confirm_send_bug_report": "Send bug report?",
    "errors_text": "error's text",
    "psittacus_bug_report": "Psittacus Bug Report",
    "send_bug_report": "Send Bug Report",
    "bug_reports": "Bug Reports",
    "bug_report_is": "If you find a problem, you can send us a bug report via email:",
    "issue_is": "Alternatively, you can file it as an issue on Psittacus's official Github repo:",
    "file_issue": "File an issue",
    "revise_with_lesson_scheduler": "Review",
    "lessons_history": "Lessons History",
    "revise_with_lesson_scheduler_is": "Let your current Lesson Scheduler decide what Lesson(s)/part of Lesson(s) you should review right now.",
    "history_here": "Lessons you've taken in the past will appear here:",
    "until_all_correct_PS": "Eventually starts re-playing the propositions that you got wrong, and won't let you go until you get them all right.",
    "worst_first_PS": "Remembers the propositions you struggled the most with last time, and plays them first.",
    "mixed_worst_lesson_LS": "Combines the propositions you struggled the most with from many different lessons you already took.",
    "oldest_lesson_first_LS": "Lets you re-take the single oldest lesson you took.",
    "worst_lesson_first_LS": "Lets you re-take the single lesson you struggled the most with.",
    "developer_options": "Developer Options",
    "enable": "Enable",
    "caution_enabling_developer_options": "CAUTION: enabling developer options may expose you to SECURITY RISKS.",
    "run_custom_code": "Run custom code",
    "caution_running_custom_code": "Running code from untrusted sources is DANGEROUS: make sure you know what you're doing!",
    "add_custom_proposition_scheduler": "Add Custom Proposition Scheduler",
    "add_custom_lesson_scheduler": "Add Custom Lesson Scheduler",
    "template": "Template",
    "click_reload_or_remove_custom_code": "Click 'Reload' after adding custom code, or 'Remove All Custom Code' if you change your mind.",
    "remove_all_custom_code": "Remove All Custom Code",
    "dev_options_reload": "Reload",
    "target_language": "Target Language",
    "source_language": "Source Language",
    "author": "Author",
    "title": "Title",
    "filters": "Filters",
    "are_you_sure_delete_progress": "Are you sure you want to delete your progress?",
    "are_you_sure_enable_dev_options": "Enable dev-mode? This may expose you to security risks!",
    "download_lessons": "Download Lessons",
    "here_you_can_search_for_and_download": "Here you can search for and download lessons hosted on this server.",
    "images_sounds": "Images/Sounds",
    "attribs_link": "https://github.com/aiman-al-masoud/psittacus/blob/main/psittacus/app/res/attribs.md",
    "click_to_open": "Click to Open",
    "current_sentence": "Current Sentence / Total Sentences",
    "target_to_native": "Target to Native",
    "input_type_is": "Choose whether to type in your solution, or to use word tips provided by the lesson.",

}