import {Proposition} from "./proposition.js"

/**
 * A lesson is mainly a list of Propositions.
 * The constructor takes the json generated by a LessonBuilder.
 */
export default class Lesson{

    constructor(jsonData){
        this.propositions = jsonData.propositions.map( p => {return new Proposition(p)} )
        this.iterator = this.propositions.values()
        this.next()
        this.lesson_over = false
    }

    next(){
        this.current = this.iterator.next().value
        
        if(!this.current){ //if undefined
            this.lesson_over = true
        }         

    }

    getCurrent(){
        return this.current   ??this.propositions[this.propositions.length-1]
    }

    isOver(){
        return this.lesson_over
    }


    getScore(){
        return parseInt(this.propositions.map((p)=>{return p.getScore()}).reduce((a,b)=>{return a+b })/this.propositions.length)
    }


}
