import {Proposition} from "./proposition.js"

/**
 * A lesson is mainly a list of Propositions.
 * The constructor takes the json generated by a LessonBuilder.
 */
export default class Lesson{

    constructor(jsonData){
        this.propositions = jsonData.propositions.map( p => {return new Proposition(p)} )
        // this.targetLanguage = jsonData.target_language??""
        // this.sourceLanguage = jsonData.source_language??""
        // this.author = jsonData.author??""
        
        this.iterator = this.propositions.values()
        this.next()
    }

    next(){
        this.current = this.iterator.next().value
        
        if(!this.current){ //if undefined
            throw new Error("reached end of lesson")
        } 

    }

    getCurrent(){
        return this.current
    }

}
